apiVersion: v1
kind: Pod
metadata:
  name: cv-model
spec:
  containers:
  - name: name
    image: ghcr.io/aniccadeveloper/cv_models_prod:docker
    imagePullPolicy: Always
  imagePullSecrets:
  - name: dockerconfigjson-github-com












[25/04 22:08] Braulio Chavez
az provider register --namespace Microsoft.KubernetesConfiguration
 surprised 1

[25/04 22:09] Braulio Chavez
az provider register --namespace Microsoft.ExtendedLocation

[25/04 22:13] Braulio Chavez
az provider show -n Microsoft.Kubernetes -o table

[25/04 22:16] Braulio Chavez
az extension add --name connectedk8s 

[25/04 22:17] Braulio Chavez
az connectedk8s connect --name k8sonse350 --resource-group arck8s_rg

[25/04 22:26] Braulio Chavez
microk8s kubectl create serviceaccount admin-user

[25/04 22:27] Braulio Chavez
microk8s kubectl create clusterrolebinding admin-user-binding --clusterrole cluster-admin --serviceaccount default:admin-user

[25/04 22:27] Braulio Chavez
SECRET_NAME=$(kubectl get serviceaccount admin-user -o jsonpath='{$.secrets[0].name}')

[25/04 22:29] Braulio Chavez
$(microk8s kubectl get serviceaccount admin-user -o jsonpath='{$.secrets[0].name}')

[25/04 22:31] Braulio Chavez
sudo microk8s kubectl get secret admin-user-token-bb44p -o jsonpath='{$.data.token}' | base64 -d | sed $'s/$/\\\n/g')

