apiVersion: v1
kind: Pod
metadata:
  name: cv-model
spec:
  containers:
  - name: name
    image: ghcr.io/aniccadeveloper/cv_models_prod:docker
    imagePullPolicy: Always
  imagePullSecrets:
  - name: dockerconfigjson-github-com

