apiVersion: v1
kind: Pod
metadata:
  name: front-counter
  labels:
    app: front-counter
spec:
  containers:
    - name: front-counter
      image: ghcr.io/aniccadeveloper/cv_models_prod:master
      imagePullPolicy: Always
      resources:
        nvidia.com/gpu: 1
  imagePullSecrets:
  - name: regcred

