kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
  labels:
    app: app-name
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZVzVwWTJOaFpHVjJaV3h2Y0dWeU9tZG9jRjl0TVdka1pVbDNTbmxZYW00NVIzTnJabTF6ZDB4bE5FcGhiMkZvU0ZNd1JHWnhkM0U9IgoJCX0KCX0KfQ==