version: 2
services:
  metrics:
    image: ghcr.io/anicca-computer-vision/cv-metric-service:main
    ports:
    - 1125:1125
  dashboard:
    image: ghcr.io/anicca-computer-vision/computer_vision_dashboard_ui:main
    ports:
    - 3000:3000