apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akvprovider-demo
spec:
  provider: azure
  secretObjects:
  - secretName: demo-secret
    type: Opaque
    data:
    - objectName: DemoSecret
      key: DemoSecret   
  parameters:
    usePodIdentity: "false"
    keyvaultName: sap-aks-keyvault
    objects:  |
      array:
        - |
          objectName: DemoSecret
          objectType: secret             # object types: secret, key or cert
          objectVersion: ""              # [OPTIONAL] object versions, default to latest if empty
    tenantId: 1ec479a1-f367-4fce-a113-606804fc463f   
